# Generated by Django 3.1.3 on 2020-11-27 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('amigosecreto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
