# Generated by Django 3.1.3 on 2020-11-29 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amigosecreto', '0002_auto_20201127_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='gift_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amigosecreto.friend'),
            preserve_default=False,
        ),
    ]
